// Copyright (c) 2023-2024 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0


= Email Notifications

OpFab can send card notifications via email. These notifications are sent when a new card is published for a user and remains unread for a configured period. The email subject includes the card title, summary, and start and end dates.

== Configuring Email Notifications

Users can enable email notifications in their user settings. They must provide an email address for receiving notifications and select the processes/states they want to be notified about.
Users can specify the desired timezone for displaying dates and times in emails. To do this, they must fill in
the "timezone for mails" field in the user settings screen.

== Email Content

The email body contains a link to the card details in OpFab. In the config.json file containing the state definition, the "emailBodyTemplate" field allows to define a template specific to the email body content.
This template can use handlebars helpers for formatting but can't run javascript. If no template is specified, the mail is sent with just the link to the card in the body.

== Email templates
In email handlebars templates it is possible to refer card fields by prefixing with "card" prefix. For example:

....
<div id="apogee-contingencies">
  {{#card.data.networkContingencies}}
....

A specific handlebars helper `deltaToHtml` allows to display rich text content from a card containing the 'richMessage' field with the following syntax:

....

{{{ deltaToHtml card.data.richMessage }}}

....

Ensure to encapsulate the expression within three curly braces to prevent HTML escaping.


It is also possible to configure custom parameters to be used in handlebars email templates.
The custom parameter can be added in cards-external-diffusion configuration under the "defaultConfig.customConfig" section:

```
cardsExternalDiffusion:
    adminPort: 2106
    activeOnStartup: true
    defaultConfig:
      mailFrom: opfab@localhost.it
      subjectPrefix: 'Opfab card received '
      customConfig: 
             myParam1: 'myValue1'
             myParam2: 'myValue2'
```
The custom parameters can then be referred in handlebars template prefixed with "config", for example:
....
{{#config.myParam1}}
....

