// Copyright (c) 2024 RTE (http://www.rte-france.com)
// See AUTHORS.txt
// This document is subject to the terms of the Creative Commons Attribution 4.0 International license.
// If a copy of the license was not distributed with this
// file, You can obtain one at https://creativecommons.org/licenses/by/4.0/.
// SPDX-License-Identifier: CC-BY-4.0

= Migration Guide from release 4.5.X to release 4.6.0

== Deprecated `toNotify` field

The card field `toNotify` is deprecated. You should use the `actions` field including "STORE_ONLY_IN_ARCHIVES" action instead.

== New line added between opfab fields and template in usercard form

A new line (<br/>) has been added in the usercard form, between the opfab fields (service/process/state or severity or
dates fields (depending on which fields are visible or not)) and the display of the template. So you have to check that
the display of your usercard form still suits you.

== Timeline domain TR renamed RT

To be consistent, the timeline domain TR has been renamed RT (Real Time).
So if necessary, you have to update your config file `web-ui.json`, replacing value `TR` with `RT` in the field
`feed.timeline.domains`, for example :
----
 "timeline": {
   "domains": [
     "RT",
     "J",
     "7D",
     "W",
     "M",
     "Y"
   ]
 }
----

== UI archives and logging number of lines per page
Since it is now possible to select the number of lines per page displayed in the archive and logging screens, the configuration parameters `archive.filters.page.size` and `logging.filters.page.size` are no longer needed and can be removed from the web-ui.json file.