
name: Test with old mongo version

on:
  schedule:
    # launch a build every day on develop
    - cron:  '0 23 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      
      - name: Job  status
        run: | 
          export OF_VERSION=$(<VERSION)
          echo "----------------------------"
          echo "Trigger by  : ${{ github.event_name }}"
          echo "On branch : ${{ github.ref_name }} "
          echo "---------------------------"
          
      - name: Cache Gradle packages
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties','**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Install 
        run: ./CICD/github/install.sh

      - name: Build
        run: |
          ./CICD/github/build.sh
          ./CICD/github/setOldMongoVersion.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Karate tests
        run: ./CICD/github/launch_karate_tests.sh
    
      - name: Cypress tests 
        run: ./CICD/github/launch_cypress_tests.sh
      
      - name: Upload cypress screenshots
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0
        if: failure()
        with:
            name: cypress-screenshots
            path: src/test/cypress/cypress/screenshots


